apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: immigration-web
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: immigration
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: immigration-web
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/live-update: "true"
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          developer-conventions/add-source-image-label
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.apps.tanzu.vmware.com/image-source-digest: tputbrese.azurecr.io/tap1.6.2:global-immigration-web@sha256:d034b410cd8adb02e16ce4ce85a2ab05825187080593deb9cf768ba6321bd431
        developer.conventions/target-containers: workload
        local-source-proxy.apps.tanzu.vmware.com: tputbrese.azurecr.io/tap1.6.2:global-immigration-web@sha256:d034b410cd8adb02e16ce4ce85a2ab05825187080593deb9cf768ba6321bd431
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: immigration
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: immigration-web
    spec:
      containers:
      - image: tputbrese.azurecr.io/tap1.6-apps/immigration-web-global@sha256:3d68b0a13c506f05123d0b82c9563519eef373e2037798c88e5c6411e541f8ce
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

