apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rails-assets-demo-prod
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: rails-assets-demo-prod
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: rails-assets-demo-prod
spec:
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: rails-assets-demo-prod
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: rails-assets-demo-prod
    spec:
      containers:
      - env:
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              key: SECRET_KEY_BASE
              name: rails-secret-key-trev-cluster
        image: tputbrese.azurecr.io/tap1.6-apps/rails-assets-demo-prod-01-dev-sandbox@sha256:992d6979ef3df04f7d3d39f455ad05c654aaa43cfa3fedd86715fa6de4a78e25
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

